name: sheet_localization
description: Annotations for the sheet_localization_generator package.
version: 1.0.0
homepage: https://github.com/faisalramdan17/sheet_localization

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  template_string: ^0.6.0
